@startuml

entity "Evento" {
  *id : number
  --
  dataHora : Date
  titulo : string
  ministerio : Ministerios
}

entity "Lider" {
  *id : number
  --
  nome : string
  lideranca : string
}

@enduml
